/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
 
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
        
        ItemIdTb.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
        });
        
        DisplayInventory();
        MedicalStaff.setActiveButton(InventoryBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ItemIdTb = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        AddItemBtn = new javax.swing.JButton();
        UpdateItemBtn = new javax.swing.JButton();
        DeleteItemBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InventoryTable = new javax.swing.JTable();
        StockQuantityTb = new javax.swing.JTextField();
        SupplierTb = new javax.swing.JTextField();
        LocationCb = new javax.swing.JComboBox<>();
        ItemTypeCb = new javax.swing.JComboBox<>();
        ItemNameTb = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MedicalStaff_img = new javax.swing.JLabel();
        Patients_img = new javax.swing.JLabel();
        LabTests_img = new javax.swing.JLabel();
        Inventory_img = new javax.swing.JLabel();
        MedicalStaffBtn = new javax.swing.JButton();
        PatientsBtn = new javax.swing.JButton();
        LabTestsBtn = new javax.swing.JButton();
        InventoryBtn = new javax.swing.JButton();
        TreatmentBtn = new javax.swing.JButton();
        Treatment_img = new javax.swing.JLabel();
        Logout_img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Item ID");

        jLabel27.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Item Name");

        ItemIdTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        ItemIdTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ItemIdTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIdTbActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Stock Quantity");

        jLabel29.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Location");

        jLabel30.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Supplier");

        AddItemBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        AddItemBtn.setForeground(new java.awt.Color(51, 204, 0));
        AddItemBtn.setText("Add Item");
        AddItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddItemBtnMouseClicked(evt);
            }
        });
        AddItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemBtnActionPerformed(evt);
            }
        });

        UpdateItemBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        UpdateItemBtn.setForeground(new java.awt.Color(204, 204, 0));
        UpdateItemBtn.setText("Update Item");
        UpdateItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateItemBtnMouseClicked(evt);
            }
        });
        UpdateItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateItemBtnActionPerformed(evt);
            }
        });

        DeleteItemBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        DeleteItemBtn.setForeground(new java.awt.Color(255, 0, 0));
        DeleteItemBtn.setText("Delete Item");
        DeleteItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteItemBtnMouseClicked(evt);
            }
        });
        DeleteItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemBtnActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Item Type");

        InventoryTable.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        InventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Item Type", "Stock Quantity", "Location", "Supplier"
            }
        ));
        InventoryTable.setRowHeight(32);
        InventoryTable.setShowHorizontalLines(true);
        InventoryTable.setShowVerticalLines(true);
        InventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(InventoryTable);

        StockQuantityTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        StockQuantityTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StockQuantityTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockQuantityTbActionPerformed(evt);
            }
        });

        SupplierTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        SupplierTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SupplierTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierTbActionPerformed(evt);
            }
        });

        LocationCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        LocationCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Pharmacy", "Salons" }));
        LocationCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationCbActionPerformed(evt);
            }
        });

        ItemTypeCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        ItemTypeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicine", "Equipment", "Supplies" }));

        ItemNameTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        ItemNameTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ItemNameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameTbActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 526));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/hospital (2).png"))); // NOI18N

        MedicalStaff_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\nurse-male.png")); // NOI18N
        MedicalStaff_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaff_imgMouseClicked(evt);
            }
        });

        Patients_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\patient.png")); // NOI18N
        Patients_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patients_imgMouseClicked(evt);
            }
        });

        LabTests_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\atom.png")); // NOI18N
        LabTests_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTests_imgMouseClicked(evt);
            }
        });

        Inventory_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/first-aid-kit.png"))); // NOI18N
        Inventory_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_imgMouseClicked(evt);
            }
        });

        MedicalStaffBtn.setBackground(new java.awt.Color(255, 0, 0));
        MedicalStaffBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        MedicalStaffBtn.setForeground(new java.awt.Color(255, 255, 255));
        MedicalStaffBtn.setText("Medical Staff");
        MedicalStaffBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        MedicalStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaffBtnMouseClicked(evt);
            }
        });
        MedicalStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalStaffBtnActionPerformed(evt);
            }
        });

        PatientsBtn.setBackground(new java.awt.Color(255, 0, 0));
        PatientsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PatientsBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientsBtn.setText("Patients");
        PatientsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PatientsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        PatientsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientsBtnMouseClicked(evt);
            }
        });
        PatientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsBtnActionPerformed(evt);
            }
        });

        LabTestsBtn.setBackground(new java.awt.Color(255, 0, 0));
        LabTestsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        LabTestsBtn.setForeground(new java.awt.Color(255, 255, 255));
        LabTestsBtn.setText("Lab Tests");
        LabTestsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        LabTestsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTestsBtnMouseClicked(evt);
            }
        });
        LabTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabTestsBtnActionPerformed(evt);
            }
        });

        InventoryBtn.setBackground(new java.awt.Color(255, 0, 0));
        InventoryBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        InventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        InventoryBtn.setText("Inventory");
        InventoryBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        InventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseClicked(evt);
            }
        });
        InventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryBtnActionPerformed(evt);
            }
        });

        TreatmentBtn.setBackground(new java.awt.Color(255, 0, 0));
        TreatmentBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TreatmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        TreatmentBtn.setText("Treatment");
        TreatmentBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        TreatmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentBtnMouseClicked(evt);
            }
        });
        TreatmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreatmentBtnActionPerformed(evt);
            }
        });

        Treatment_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/remedy.png"))); // NOI18N
        Treatment_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Treatment_imgMouseClicked(evt);
            }
        });

        Logout_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/entry-door.png"))); // NOI18N
        Logout_img1.setAlignmentY(0.0F);
        Logout_img1.setMaximumSize(new java.awt.Dimension(50, 50));
        Logout_img1.setMinimumSize(new java.awt.Dimension(50, 50));
        Logout_img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_img1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MedicalStaff_img)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PatientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabTestsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TreatmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Patients_img)
                        .addGap(132, 132, 132))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabTests_img, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Inventory_img, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Treatment_img)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(MedicalStaff_img)
                .addGap(0, 0, 0)
                .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Patients_img)
                .addGap(0, 0, 0)
                .addComponent(PatientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(LabTests_img)
                .addGap(0, 0, 0)
                .addComponent(LabTestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Inventory_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Treatment_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TreatmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StockQuantityTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemTypeCb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ItemNameTb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemTypeCb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockQuantityTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LocationCb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SupplierTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(UpdateItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(DeleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    PreparedStatement pst = null;
    
    // Functia pentru afisarea obiectelor din inventar in InventoryTable
private void DisplayInventory() {
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        String Query = "SELECT * FROM inventory";
        St = Con.createStatement();
        Rs = St.executeQuery(Query);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Item ID");
        model.addColumn("Item Name");
        model.addColumn("Item Type");
        model.addColumn("Stock Quantity");
        model.addColumn("Location");
        model.addColumn("Supplier");

        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("item_id"),
                Rs.getString("item_name"),
                Rs.getString("item_type"),
                Rs.getInt("stock_quantity"),
                Rs.getString("location"),
                Rs.getString("supplier")
            });
        }
        InventoryTable.setModel(model);

        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void filterById() {
    String prefix = ItemIdTb.getText().trim();

    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

        // Daca prefixul este gol, afisam tot
        if (prefix.isEmpty()) {
            DisplayInventory();
        } else {
            // Construim interogarea cu LIKE pentru a potrivi prefixul
            String query = "SELECT * FROM inventory WHERE CAST(item_id AS CHAR) LIKE ?";
            pst = Con.prepareStatement(query);
            pst.setString(1, prefix + "%"); // orice ID care începe cu prefix

            Rs = pst.executeQuery();

            // Construim un DefaultTableModel cu coloanele personalizate
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Item ID");
            model.addColumn("Item Name");
            model.addColumn("Item Type");
            model.addColumn("Stock Quantity");
            model.addColumn("Location");
            model.addColumn("Supplier");

            // Adaugam randurile rezultate
            while (Rs.next()) {
                model.addRow(new Object[]{
                    Rs.getInt("item_id"),
                    Rs.getString("item_name"),
                    Rs.getString("item_type"),
                    Rs.getInt("stock_quantity"),
                    Rs.getString("location"),
                    Rs.getString("supplier")
                });
            }

            // Actualizam tabelul
            InventoryTable.setModel(model);
        }

        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    private void ItemIdTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIdTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemIdTbActionPerformed

    private void AddItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddItemBtnActionPerformed

    private void UpdateItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateItemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateItemBtnActionPerformed

    private void DeleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteItemBtnActionPerformed

    private void StockQuantityTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockQuantityTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockQuantityTbActionPerformed

    private void SupplierTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierTbActionPerformed

    private void LocationCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationCbActionPerformed

    private void ItemNameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNameTbActionPerformed

    private int Key = 0;
    
   private void Clear() {
    ItemIdTb.setText("");
    ItemNameTb.setText("");
    StockQuantityTb.setText("");
    SupplierTb.setText("");
    ItemTypeCb.setSelectedIndex(0);
    LocationCb.setSelectedIndex(0);
    Key = 0;
} 
   
    
    private void AddItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItemBtnMouseClicked
        if (ItemIdTb.getText().isEmpty() || ItemNameTb.getText().isEmpty() || StockQuantityTb.getText().isEmpty() || SupplierTb.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Missing Information");
    } else {
        try {
            boolean isItemIdValid = true;
            boolean isStockQuantityValid = true;

            int itemId = 0;
            int stockQuantity = 0;

            // Validare pentru Item ID
            try {
                itemId = Integer.parseInt(ItemIdTb.getText());
            } catch (NumberFormatException e) {
                isItemIdValid = false;
            }

            // Validare pentru Stock Quantity
            try {
                stockQuantity = Integer.parseInt(StockQuantityTb.getText());
            } catch (NumberFormatException e) {
                isStockQuantityValid = false;
            }

            // Gestionam cazurile posibile pentru mesaje de eroare
            if (!isItemIdValid && !isStockQuantityValid) {
                JOptionPane.showMessageDialog(this, "Please enter valid numbers for both Item ID and Stock Quantity.");
                return;
            } else if (!isItemIdValid) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number for Item ID.");
                return;
            } else if (!isStockQuantityValid) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number for Stock Quantity.");
                return;
            }

            // Conectare la baza de date
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

            // Verificam daca obiectul exista deja
            String CheckQuery = "SELECT * FROM inventory WHERE item_id = ?";
            PreparedStatement CheckStmt = Con.prepareStatement(CheckQuery);
            CheckStmt.setInt(1, itemId);
            Rs = CheckStmt.executeQuery();

            if (Rs.next()) {
                JOptionPane.showMessageDialog(this, "Item with this ID already exists. Use Update to modify it.");
            } else {
                // Inseram un nou obiect in baza de date
                String InsertQuery = "INSERT INTO inventory (item_id, item_name, item_type, stock_quantity, location, supplier) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement Add = Con.prepareStatement(InsertQuery);
                Add.setInt(1, itemId);
                Add.setString(2, ItemNameTb.getText());
                Add.setString(3, ItemTypeCb.getSelectedItem().toString());
                Add.setInt(4, stockQuantity);
                Add.setString(5, LocationCb.getSelectedItem().toString());
                Add.setString(6, SupplierTb.getText());

                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item Added Successfully");

                // Reimprospatam tabelul și golim campurile
                DisplayInventory();
                Clear();
            }
            Con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_AddItemBtnMouseClicked

    private void UpdateItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateItemBtnMouseClicked
        if (Key == 0) {
        JOptionPane.showMessageDialog(this, "Select an Item to Update");
    } else {
        try {
            int stockQuantity = Integer.parseInt(StockQuantityTb.getText());
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
            String UpdateQuery = "UPDATE inventory SET item_name = ?, item_type = ?, stock_quantity = ?, location = ?, supplier = ? WHERE item_id = ?";
            PreparedStatement Update = Con.prepareStatement(UpdateQuery);
            Update.setString(1, ItemNameTb.getText());
            Update.setString(2, ItemTypeCb.getSelectedItem().toString());
            Update.setInt(3, stockQuantity);
            Update.setString(4, LocationCb.getSelectedItem().toString());
            Update.setString(5, SupplierTb.getText());
            Update.setInt(6, Key);
            int row = Update.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item Updated Successfully");
            DisplayInventory();
            Clear();
            Con.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for Stock Quantity.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_UpdateItemBtnMouseClicked

    
    private void DeleteItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteItemBtnMouseClicked
        if (Key == 0) {
        JOptionPane.showMessageDialog(this, "Select an Item to Delete");
    } else {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
            String DeleteQuery = "DELETE FROM inventory WHERE item_id = ?";
            PreparedStatement Delete = Con.prepareStatement(DeleteQuery);
            Delete.setInt(1, Key);
            int row = Delete.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item Deleted Successfully");
            DisplayInventory();
            Clear();
            Con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_DeleteItemBtnMouseClicked

    private void InventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) InventoryTable.getModel();
    int MyIndex = InventoryTable.getSelectedRow();
    
    // Setează valorile din rândul selectat în câmpurile corespunzătoare
    ItemIdTb.setText(model.getValueAt(MyIndex, 0).toString()); // Item ID
    ItemNameTb.setText(model.getValueAt(MyIndex, 1).toString()); // Item Name
    ItemTypeCb.setSelectedItem(model.getValueAt(MyIndex, 2).toString()); // Item Type
    StockQuantityTb.setText(model.getValueAt(MyIndex, 3).toString()); // Stock Quantity
    LocationCb.setSelectedItem(model.getValueAt(MyIndex, 4).toString()); // Location
    SupplierTb.setText(model.getValueAt(MyIndex, 5).toString()); // Supplier
    
    // Stocheaza cheia pentru identificare
    Key = Integer.parseInt(model.getValueAt(MyIndex, 0).toString()); // Item ID (cheia principală)
    }//GEN-LAST:event_InventoryTableMouseClicked

    private void MedicalStaff_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaff_imgMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaff_imgMouseClicked

    private void Patients_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patients_imgMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Patients_imgMouseClicked

    private void LabTests_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTests_imgMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTests_imgMouseClicked

    private void Inventory_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_imgMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Inventory_imgMouseClicked

    private void MedicalStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaffBtnMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaffBtnMouseClicked

    private void MedicalStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalStaffBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalStaffBtnActionPerformed

    private void PatientsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientsBtnMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientsBtnMouseClicked

    private void PatientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsBtnActionPerformed

    private void LabTestsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTestsBtnMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTestsBtnMouseClicked

    private void LabTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabTestsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabTestsBtnActionPerformed

    private void InventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventoryBtnMouseClicked

    private void InventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryBtnActionPerformed

    private void TreatmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentBtnMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TreatmentBtnMouseClicked

    private void TreatmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreatmentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TreatmentBtnActionPerformed

    private void Treatment_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Treatment_imgMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Treatment_imgMouseClicked

    private void Logout_img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_img1MouseClicked
        if (JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to leave?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
        ) == JOptionPane.YES_OPTION) {
        new Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_Logout_img1MouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemBtn;
    private javax.swing.JButton DeleteItemBtn;
    private javax.swing.JButton InventoryBtn;
    private javax.swing.JTable InventoryTable;
    private javax.swing.JLabel Inventory_img;
    private javax.swing.JTextField ItemIdTb;
    private javax.swing.JTextField ItemNameTb;
    private javax.swing.JComboBox<String> ItemTypeCb;
    private javax.swing.JButton LabTestsBtn;
    private javax.swing.JLabel LabTests_img;
    private javax.swing.JComboBox<String> LocationCb;
    private javax.swing.JLabel Logout_img1;
    private javax.swing.JButton MedicalStaffBtn;
    private javax.swing.JLabel MedicalStaff_img;
    private javax.swing.JButton PatientsBtn;
    private javax.swing.JLabel Patients_img;
    private javax.swing.JTextField StockQuantityTb;
    private javax.swing.JTextField SupplierTb;
    private javax.swing.JButton TreatmentBtn;
    private javax.swing.JLabel Treatment_img;
    private javax.swing.JButton UpdateItemBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
