/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.HashMap;
import net.proteanit.sql.DbUtils;


public class LabTests extends javax.swing.JFrame {

    public LabTests() {
        initComponents();
        setupListeners();
        populateTestDepartmentMap();
        DisplayPatients("Cardiology");
        DisplayDoctors("Cardiology");
        DisplayTechnicians("Cardiology");
        DisplayLabTests();
        MedicalStaff.setActiveButton(LabTestsBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TStatusCb = new javax.swing.JComboBox<>();
        AddTestBtn = new javax.swing.JButton();
        UpdateTestBtn = new javax.swing.JButton();
        DeleteTestBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LabTestsTable = new javax.swing.JTable();
        TNameCb = new javax.swing.JComboBox<>();
        TDepartmentCb = new javax.swing.JComboBox<>();
        TIdTb = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DoctorsTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TechniciansTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        PatientsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MedicalStaff_img = new javax.swing.JLabel();
        Patients_img = new javax.swing.JLabel();
        LabTests_img = new javax.swing.JLabel();
        Inventory_img = new javax.swing.JLabel();
        MedicalStaffBtn = new javax.swing.JButton();
        PatientsBtn = new javax.swing.JButton();
        LabTestsBtn = new javax.swing.JButton();
        InventoryBtn = new javax.swing.JButton();
        TreatmentBtn = new javax.swing.JButton();
        Treatment_img = new javax.swing.JLabel();
        Logout_img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Test ID");

        jLabel27.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Patient");

        jLabel28.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Doctor in Charge");

        jLabel29.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Laboratory Technician");

        jLabel30.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Test Status");

        TStatusCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TStatusCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "In Progress", "Cancelled", "Normal", "Abnormal", "Positive", "Negative", "Critical" }));
        TStatusCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TStatusCbActionPerformed(evt);
            }
        });

        AddTestBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        AddTestBtn.setForeground(new java.awt.Color(51, 204, 0));
        AddTestBtn.setText("Add Lab Test");
        AddTestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTestBtnMouseClicked(evt);
            }
        });
        AddTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTestBtnActionPerformed(evt);
            }
        });

        UpdateTestBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        UpdateTestBtn.setForeground(new java.awt.Color(204, 204, 0));
        UpdateTestBtn.setText("Update Lab Test");
        UpdateTestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateTestBtnMouseClicked(evt);
            }
        });
        UpdateTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTestBtnActionPerformed(evt);
            }
        });

        DeleteTestBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        DeleteTestBtn.setForeground(new java.awt.Color(255, 0, 0));
        DeleteTestBtn.setText("Delete Lab Test");
        DeleteTestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteTestBtnMouseClicked(evt);
            }
        });
        DeleteTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTestBtnActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Department");

        LabTestsTable.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        LabTestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test ID", "Patient ID", "Test Name", "Department", "Doctor ID", "Technician ID", "Test Status"
            }
        ));
        LabTestsTable.setRowHeight(32);
        LabTestsTable.setShowHorizontalLines(true);
        LabTestsTable.setShowVerticalLines(true);
        LabTestsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTestsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(LabTestsTable);

        TNameCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TNameCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrocardiogram", "Magnetic Resonance Img", "Skin Biopsy", "Electroencephalogram", "Visual Field Test", "Newborn Screening", "Urinalysis", "Thyroid Function Test" }));
        TNameCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNameCbActionPerformed(evt);
            }
        });

        TDepartmentCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TDepartmentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "Radiology", "Dermatology", "Neurology", "Ophthalmology", "Pediatrics", "Urology", "Endocrinology", "" }));
        TDepartmentCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDepartmentCbActionPerformed(evt);
            }
        });

        TIdTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TIdTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TIdTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdTbActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Test Name");

        DoctorsTable.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        DoctorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee Phone", "Employee Address", "Employee Position", "Department"
            }
        ));
        DoctorsTable.setRowHeight(32);
        DoctorsTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        DoctorsTable.setShowHorizontalLines(true);
        DoctorsTable.setShowVerticalLines(true);
        jScrollPane4.setViewportView(DoctorsTable);

        TechniciansTable.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TechniciansTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee Phone", "Employee Address", "Employee Position", "Department"
            }
        ));
        TechniciansTable.setRowHeight(32);
        TechniciansTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        TechniciansTable.setShowHorizontalLines(true);
        TechniciansTable.setShowVerticalLines(true);
        jScrollPane5.setViewportView(TechniciansTable);

        PatientsTable.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PatientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Patient Phone", "Patient Address", "Gender", "Department"
            }
        ));
        PatientsTable.setRowHeight(32);
        PatientsTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane6.setViewportView(PatientsTable);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 526));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/hospital (2).png"))); // NOI18N

        MedicalStaff_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\nurse-male.png")); // NOI18N
        MedicalStaff_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaff_imgMouseClicked(evt);
            }
        });

        Patients_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\patient.png")); // NOI18N
        Patients_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patients_imgMouseClicked(evt);
            }
        });

        LabTests_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\atom.png")); // NOI18N
        LabTests_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTests_imgMouseClicked(evt);
            }
        });

        Inventory_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/first-aid-kit.png"))); // NOI18N
        Inventory_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_imgMouseClicked(evt);
            }
        });

        MedicalStaffBtn.setBackground(new java.awt.Color(255, 0, 0));
        MedicalStaffBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        MedicalStaffBtn.setForeground(new java.awt.Color(255, 255, 255));
        MedicalStaffBtn.setText("Medical Staff");
        MedicalStaffBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        MedicalStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaffBtnMouseClicked(evt);
            }
        });
        MedicalStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalStaffBtnActionPerformed(evt);
            }
        });

        PatientsBtn.setBackground(new java.awt.Color(255, 0, 0));
        PatientsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PatientsBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientsBtn.setText("Patients");
        PatientsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PatientsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        PatientsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientsBtnMouseClicked(evt);
            }
        });
        PatientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsBtnActionPerformed(evt);
            }
        });

        LabTestsBtn.setBackground(new java.awt.Color(255, 0, 0));
        LabTestsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        LabTestsBtn.setForeground(new java.awt.Color(255, 255, 255));
        LabTestsBtn.setText("Lab Tests");
        LabTestsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        LabTestsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTestsBtnMouseClicked(evt);
            }
        });
        LabTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabTestsBtnActionPerformed(evt);
            }
        });

        InventoryBtn.setBackground(new java.awt.Color(255, 0, 0));
        InventoryBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        InventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        InventoryBtn.setText("Inventory");
        InventoryBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        InventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseClicked(evt);
            }
        });
        InventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryBtnActionPerformed(evt);
            }
        });

        TreatmentBtn.setBackground(new java.awt.Color(255, 0, 0));
        TreatmentBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TreatmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        TreatmentBtn.setText("Treatment");
        TreatmentBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        TreatmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentBtnMouseClicked(evt);
            }
        });
        TreatmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreatmentBtnActionPerformed(evt);
            }
        });

        Treatment_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/remedy.png"))); // NOI18N
        Treatment_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Treatment_imgMouseClicked(evt);
            }
        });

        Logout_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/entry-door.png"))); // NOI18N
        Logout_img1.setAlignmentY(0.0F);
        Logout_img1.setMaximumSize(new java.awt.Dimension(50, 50));
        Logout_img1.setMinimumSize(new java.awt.Dimension(50, 50));
        Logout_img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_img1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MedicalStaff_img)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PatientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabTestsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TreatmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Patients_img)
                        .addGap(132, 132, 132))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabTests_img, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Inventory_img, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Treatment_img)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(MedicalStaff_img)
                .addGap(0, 0, 0)
                .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Patients_img)
                .addGap(0, 0, 0)
                .addComponent(PatientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(LabTests_img)
                .addGap(0, 0, 0)
                .addComponent(LabTestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Inventory_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Treatment_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TreatmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TNameCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TDepartmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TStatusCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(AddTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(UpdateTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(171, 171, 171)
                                            .addComponent(DeleteTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(439, 439, 439))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(440, 440, 440))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TNameCb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TDepartmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TStatusCb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TIdTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIdTbActionPerformed

    private void TDepartmentCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDepartmentCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TDepartmentCbActionPerformed

    private void TNameCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNameCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNameCbActionPerformed

    private void LabTestsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTestsTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) LabTestsTable.getModel();
        int MyIndex = LabTestsTable.getSelectedRow();

        // Preluarea datele din randul selectat
        TIdTb.setText(model.getValueAt(MyIndex, 0).toString()); // Test ID
        TNameCb.setSelectedItem(model.getValueAt(MyIndex, 2).toString()); // Test Name
        TDepartmentCb.setSelectedItem(model.getValueAt(MyIndex, 3).toString()); // Department
        TStatusCb.setSelectedItem(model.getValueAt(MyIndex, 6).toString()); // Test Status

        int patientId = Integer.parseInt(model.getValueAt(MyIndex, 1).toString()); // Patient ID
        int doctorId = Integer.parseInt(model.getValueAt(MyIndex, 4).toString()); // Doctor ID
        int technicianId = Integer.parseInt(model.getValueAt(MyIndex, 5).toString()); // Technician ID

        // Selectarea pacientul in tabelul PatientsTable
        for (int i = 0; i < PatientsTable.getRowCount(); i++) {
            if (Integer.parseInt(PatientsTable.getValueAt(i, 0).toString()) == patientId) {
                PatientsTable.setRowSelectionInterval(i, i);
                break;
            }
        }

        // Selectarea doctorul în tabelul DoctorsTable
        for (int i = 0; i < DoctorsTable.getRowCount(); i++) {
            if (Integer.parseInt(DoctorsTable.getValueAt(i, 0).toString()) == doctorId) {
                DoctorsTable.setRowSelectionInterval(i, i);
                break;
            }
        }

        // Selectam tehnicianul in tabelul TechniciansTable
        for (int i = 0; i < TechniciansTable.getRowCount(); i++) {
            if (Integer.parseInt(TechniciansTable.getValueAt(i, 0).toString()) == technicianId) {
                TechniciansTable.setRowSelectionInterval(i, i);
                break;
            }
        }
    }//GEN-LAST:event_LabTestsTableMouseClicked

    private void DeleteTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteTestBtnActionPerformed

    private void DeleteTestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteTestBtnMouseClicked
        if (TIdTb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                int testId = Integer.parseInt(TIdTb.getText());
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
                String deleteQuery = "DELETE FROM lab_tests WHERE test_id = ?";
                pst = Con.prepareStatement(deleteQuery);
                pst.setInt(1, testId);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Test Deleted Successfully");
                DisplayLabTests();
                Clear();
                Con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_DeleteTestBtnMouseClicked

    private void UpdateTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateTestBtnActionPerformed

    private void UpdateTestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateTestBtnMouseClicked
        if (TIdTb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                int testId = Integer.parseInt(TIdTb.getText());
                String patientId = PatientsTable.getValueAt(PatientsTable.getSelectedRow(), 0).toString();
                String doctorId = DoctorsTable.getValueAt(DoctorsTable.getSelectedRow(), 0).toString();
                String technicianId = TechniciansTable.getValueAt(TechniciansTable.getSelectedRow(), 0).toString();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

                String updateQuery = "UPDATE lab_tests SET patient_id = ?, test_name = ?, department = ?, employee1_id = ?, employee2_id = ?, status = ? WHERE test_id = ?";
                pst = Con.prepareStatement(updateQuery);
                pst.setInt(1, Integer.parseInt(patientId));
                pst.setString(2, (String) TNameCb.getSelectedItem());
                pst.setString(3, (String) TDepartmentCb.getSelectedItem());
                pst.setInt(4, Integer.parseInt(doctorId));
                pst.setInt(5, Integer.parseInt(technicianId));
                pst.setString(6, (String) TStatusCb.getSelectedItem());
                pst.setInt(7, testId);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Test Updated Successfully");
                DisplayLabTests();
                Clear();
                Con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_UpdateTestBtnMouseClicked

    private void AddTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTestBtnActionPerformed

    private void AddTestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTestBtnMouseClicked
        if (TIdTb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                int testId = Integer.parseInt(TIdTb.getText());
                String patientId = PatientsTable.getValueAt(PatientsTable.getSelectedRow(), 0).toString();
                String doctorId = DoctorsTable.getValueAt(DoctorsTable.getSelectedRow(), 0).toString();
                String technicianId = TechniciansTable.getValueAt(TechniciansTable.getSelectedRow(), 0).toString();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

                String query = "SELECT * FROM lab_tests WHERE test_id = ?";
                pst = Con.prepareStatement(query);
                pst.setInt(1, testId);
                Rs = pst.executeQuery();
                if (Rs.next()) {
                    JOptionPane.showMessageDialog(this, "Test ID already exists. Please use Update instead.");
                } else {
                    String insertQuery = "INSERT INTO lab_tests (test_id, patient_id, test_name, department, employee1_id, employee2_id, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
                    pst = Con.prepareStatement(insertQuery);
                    pst.setInt(1, testId);
                    pst.setInt(2, Integer.parseInt(patientId));
                    pst.setString(3, (String) TNameCb.getSelectedItem());
                    pst.setString(4, (String) TDepartmentCb.getSelectedItem());
                    pst.setInt(5, Integer.parseInt(doctorId));
                    pst.setInt(6, Integer.parseInt(technicianId));
                    pst.setString(7, (String) TStatusCb.getSelectedItem());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Test Added Successfully");
                    DisplayLabTests();
                    Clear();
                }
                Con.close();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Test ID.");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_AddTestBtnMouseClicked

    private void TStatusCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TStatusCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TStatusCbActionPerformed

    private void MedicalStaff_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaff_imgMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaff_imgMouseClicked

    private void Patients_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patients_imgMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Patients_imgMouseClicked

    private void LabTests_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTests_imgMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTests_imgMouseClicked

    private void Inventory_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_imgMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Inventory_imgMouseClicked

    private void MedicalStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaffBtnMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaffBtnMouseClicked

    private void MedicalStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalStaffBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalStaffBtnActionPerformed

    private void PatientsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientsBtnMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientsBtnMouseClicked

    private void PatientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsBtnActionPerformed

    private void LabTestsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTestsBtnMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTestsBtnMouseClicked

    private void LabTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabTestsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabTestsBtnActionPerformed

    private void InventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventoryBtnMouseClicked

    private void InventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryBtnActionPerformed

    private void TreatmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentBtnMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TreatmentBtnMouseClicked

    private void TreatmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreatmentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TreatmentBtnActionPerformed

    private void Treatment_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Treatment_imgMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Treatment_imgMouseClicked

    private void Logout_img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_img1MouseClicked
        if (JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to leave?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
        ) == JOptionPane.YES_OPTION) {
        new Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_Logout_img1MouseClicked

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;
    
    // Map pentru potrivirea între Test Name și Department
HashMap<String, String> testDepartmentMap = new HashMap<>();

// Maparea intre Test Name și Department
private void populateTestDepartmentMap() {
    testDepartmentMap.put("Electrocardiogram", "Cardiology");
    testDepartmentMap.put("Magnetic Resonance Img", "Radiology");
    testDepartmentMap.put("Skin Biopsy", "Dermatology");
    testDepartmentMap.put("Electroencephalogram", "Neurology");
    testDepartmentMap.put("Visual Field Test", "Ophthalmology");
    testDepartmentMap.put("Newborn Screening", "Pediatrics");
    testDepartmentMap.put("Urinalysis", "Urology");
    testDepartmentMap.put("Thyroid Function Test", "Endocrinology");
}

// Pentru sincronizare
private void setupListeners() {
    TNameCb.addActionListener(evt -> syncTestNameAndDepartment());
    TDepartmentCb.addActionListener(evt -> syncDepartmentAndTest());
}

// Actualizeaza Test Name si Department în functie de selectia testului
private void syncTestNameAndDepartment() {
    String selectedTest = (String) TNameCb.getSelectedItem();
    String selectedDepartment = (String) TDepartmentCb.getSelectedItem();

    if (testDepartmentMap.containsKey(selectedTest)) {
        TDepartmentCb.setSelectedItem(testDepartmentMap.get(selectedTest));
        selectedDepartment = testDepartmentMap.get(selectedTest);
    } else if (testDepartmentMap.containsValue(selectedDepartment)) {
        for (String key : testDepartmentMap.keySet()) {
            if (testDepartmentMap.get(key).equals(selectedDepartment)) {
                TNameCb.setSelectedItem(key);
                break;
            }
        }
    }
    DisplayPatients(selectedDepartment);
    DisplayDoctors(selectedDepartment);
    DisplayTechnicians(selectedDepartment);
}

// Actualizeaza Test Name in functie de departamentul selectat
private void syncDepartmentAndTest() {
    String selectedDepartment = (String) TDepartmentCb.getSelectedItem();

    if (selectedDepartment != null && !selectedDepartment.isEmpty()) {
        // Gasim primul test care se potriveste cu departamentul selectat
        for (String testName : testDepartmentMap.keySet()) {
            if (testDepartmentMap.get(testName).equals(selectedDepartment)) {
                TNameCb.setSelectedItem(testName);
                break;
            }
        }
    }

    // Dupa ce se alege testul, se actualizeaza restul informatiilor (pacienti, doctori, etc.)
    DisplayPatients(selectedDepartment);
    DisplayDoctors(selectedDepartment);
    DisplayTechnicians(selectedDepartment);
}
    
    private void DisplayPatients(String department) {
     try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        String Query = "SELECT * FROM patients WHERE department = ?";
        PreparedStatement pst = Con.prepareStatement(Query);
        pst.setString(1, department);
        Rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Patient ID");
        model.addColumn("Patient Name");
        model.addColumn("Patient Phone");
        model.addColumn("Patient Address");
        model.addColumn("Gender");
        model.addColumn("Department");

        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("patient_id"),
                Rs.getString("patient_name"),
                Rs.getInt("patient_phone"),
                Rs.getString("patient_address"),
                Rs.getString("patient_gender"),
                Rs.getString("department")
            });
        }
        PatientsTable.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
            
    
    private void DisplayDoctors(String department) {
     try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        String Query = "SELECT * FROM medical_staff WHERE department = ? AND employee_position = 'Doctor'";
        PreparedStatement pst = Con.prepareStatement(Query);
        pst.setString(1, department);
        Rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Employee ID");
        model.addColumn("Employee Name");
        model.addColumn("Phone");
        model.addColumn("Address");
        model.addColumn("Position");
        model.addColumn("Department");

        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("employee_id"),
                Rs.getString("employee_name"),
                Rs.getInt("employee_phone"),
                Rs.getString("employee_address"),
                Rs.getString("employee_position"),
                Rs.getString("department")
            });
        }
        DoctorsTable.setModel(model);

        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void DisplayTechnicians(String department) {
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        String Query = "SELECT * FROM medical_staff WHERE department = ? AND employee_position = 'Technician'";
        PreparedStatement pst = Con.prepareStatement(Query);
        pst.setString(1, department);
        Rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Employee ID");
        model.addColumn("Employee Name");
        model.addColumn("Phone");
        model.addColumn("Address");
        model.addColumn("Position");
        model.addColumn("Department");

        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("employee_id"),
                Rs.getString("employee_name"),
                Rs.getInt("employee_phone"),
                Rs.getString("employee_address"),
                Rs.getString("employee_position"),
                Rs.getString("department")
            });
        }
        TechniciansTable.setModel(model);

        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    private void DisplayTests() {
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT * FROM lab_tests");
        LabTestsTable.setModel(DbUtils.resultSetToTableModel(Rs));
        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    
    private void Clear() {
    TIdTb.setText("");
    TNameCb.setSelectedIndex(0);
    TDepartmentCb.setSelectedIndex(0);
    TStatusCb.setSelectedIndex(0);
}
    
    private void DisplayLabTests() {
       try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        String Query = "SELECT * FROM lab_tests";
        St = Con.createStatement();
        Rs = St.executeQuery(Query);

        // Definirea unui model pentru tabelul LabTestsTable
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Test ID");
        model.addColumn("Patient ID");
        model.addColumn("Test Name");
        model.addColumn("Department");
        model.addColumn("Doctor ID");
        model.addColumn("Technician ID");
        model.addColumn("Test Status");

        // Adaugarea randurilor in model
        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("test_id"),
                Rs.getInt("patient_id"),
                Rs.getString("test_name"),
                Rs.getString("department"),
                Rs.getInt("employee1_id"), // Doctor ID
                Rs.getInt("employee2_id"), // Technician ID
                Rs.getString("status")
            });
        }
        LabTestsTable.setModel(model); // Setăm modelul în tabel
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabTests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTestBtn;
    private javax.swing.JButton DeleteTestBtn;
    private javax.swing.JTable DoctorsTable;
    private javax.swing.JButton InventoryBtn;
    private javax.swing.JLabel Inventory_img;
    private javax.swing.JButton LabTestsBtn;
    private javax.swing.JTable LabTestsTable;
    private javax.swing.JLabel LabTests_img;
    private javax.swing.JLabel Logout_img1;
    private javax.swing.JButton MedicalStaffBtn;
    private javax.swing.JLabel MedicalStaff_img;
    private javax.swing.JButton PatientsBtn;
    private javax.swing.JTable PatientsTable;
    private javax.swing.JLabel Patients_img;
    private javax.swing.JComboBox<String> TDepartmentCb;
    private javax.swing.JTextField TIdTb;
    private javax.swing.JComboBox<String> TNameCb;
    private javax.swing.JComboBox<String> TStatusCb;
    private javax.swing.JTable TechniciansTable;
    private javax.swing.JButton TreatmentBtn;
    private javax.swing.JLabel Treatment_img;
    private javax.swing.JButton UpdateTestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
