/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;


import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


public class MedicalStaff extends javax.swing.JFrame {
private static JButton activeButton = null; // Reținem butonul activ
    public MedicalStaff() {
        initComponents();
        
        EIdTb.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
        });
        
        DisplayMedicalStaff();
        setActiveButton(MedicalStaffBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EmployeeId = new javax.swing.JLabel();
        EIdTb = new javax.swing.JTextField();
        EmployeeName = new javax.swing.JLabel();
        ENameTb = new javax.swing.JTextField();
        EmployeeAddress = new javax.swing.JLabel();
        EAddressTb = new javax.swing.JTextField();
        EmployeePosition = new javax.swing.JLabel();
        EPositionCb = new javax.swing.JComboBox<>();
        Department = new javax.swing.JLabel();
        EDepartmentCb = new javax.swing.JComboBox<>();
        AddMedBtn = new javax.swing.JButton();
        UpdateMedBtn = new javax.swing.JButton();
        DeleteMedBtn = new javax.swing.JButton();
        EmployeePhone = new javax.swing.JLabel();
        EPhoneTb = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedicalStaffTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        MedicalStaff_img = new javax.swing.JLabel();
        Patients_img = new javax.swing.JLabel();
        LabTests_img = new javax.swing.JLabel();
        Inventory_img = new javax.swing.JLabel();
        MedicalStaffBtn = new javax.swing.JButton();
        PatientsBtn = new javax.swing.JButton();
        LabTestsBtn = new javax.swing.JButton();
        InventoryBtn = new javax.swing.JButton();
        TreatmentBtn = new javax.swing.JButton();
        Treatment_img = new javax.swing.JLabel();
        Logout_img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));

        EmployeeId.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EmployeeId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeId.setText("Employee ID");

        EIdTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EIdTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EIdTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIdTbActionPerformed(evt);
            }
        });

        EmployeeName.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EmployeeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeName.setText("Employee Name");

        ENameTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        ENameTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ENameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENameTbActionPerformed(evt);
            }
        });

        EmployeeAddress.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EmployeeAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeAddress.setText("Employee Address");

        EAddressTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EAddressTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EAddressTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAddressTbActionPerformed(evt);
            }
        });

        EmployeePosition.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EmployeePosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeePosition.setText("Employee Position");

        EPositionCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EPositionCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Assistant", "Nurse", "Technician" }));
        EPositionCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPositionCbActionPerformed(evt);
            }
        });

        Department.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        Department.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Department.setText("Department");

        EDepartmentCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EDepartmentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "Radiology", "Dermatology", "Neurology", "Ophthalmology", "Pediatrics", "Urology", "Endocrinology", "" }));
        EDepartmentCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDepartmentCbActionPerformed(evt);
            }
        });

        AddMedBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        AddMedBtn.setForeground(new java.awt.Color(51, 204, 0));
        AddMedBtn.setText("Add Medical Staff");
        AddMedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMedBtnMouseClicked(evt);
            }
        });
        AddMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMedBtnActionPerformed(evt);
            }
        });

        UpdateMedBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        UpdateMedBtn.setForeground(new java.awt.Color(204, 204, 0));
        UpdateMedBtn.setText("Update Medical Staff");
        UpdateMedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMedBtnMouseClicked(evt);
            }
        });
        UpdateMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMedBtnActionPerformed(evt);
            }
        });

        DeleteMedBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        DeleteMedBtn.setForeground(new java.awt.Color(255, 0, 0));
        DeleteMedBtn.setText("Delete Medical Staff");
        DeleteMedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMedBtnMouseClicked(evt);
            }
        });
        DeleteMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMedBtnActionPerformed(evt);
            }
        });

        EmployeePhone.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EmployeePhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeePhone.setText("Employee Phone");

        EPhoneTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        EPhoneTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EPhoneTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPhoneTbActionPerformed(evt);
            }
        });

        MedicalStaffTable.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        MedicalStaffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee Phone", "Employee Address", "Employee Position", "Department"
            }
        ));
        MedicalStaffTable.setRowHeight(32);
        MedicalStaffTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        MedicalStaffTable.setShowHorizontalLines(true);
        MedicalStaffTable.setShowVerticalLines(true);
        MedicalStaffTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaffTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MedicalStaffTable);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 526));

        Title.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("HOSPITAL MANAGEMENT SYSTEM");

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/hospital (2).png"))); // NOI18N

        MedicalStaff_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\nurse-male.png")); // NOI18N
        MedicalStaff_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaff_imgMouseClicked(evt);
            }
        });

        Patients_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\patient.png")); // NOI18N
        Patients_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patients_imgMouseClicked(evt);
            }
        });

        LabTests_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\atom.png")); // NOI18N
        LabTests_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTests_imgMouseClicked(evt);
            }
        });

        Inventory_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/first-aid-kit.png"))); // NOI18N
        Inventory_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_imgMouseClicked(evt);
            }
        });

        MedicalStaffBtn.setBackground(new java.awt.Color(255, 0, 0));
        MedicalStaffBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        MedicalStaffBtn.setForeground(new java.awt.Color(255, 255, 255));
        MedicalStaffBtn.setText("Medical Staff");
        MedicalStaffBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        MedicalStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaffBtnMouseClicked(evt);
            }
        });
        MedicalStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalStaffBtnActionPerformed(evt);
            }
        });

        PatientsBtn.setBackground(new java.awt.Color(255, 0, 0));
        PatientsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PatientsBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientsBtn.setText("Patients");
        PatientsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PatientsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        PatientsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientsBtnMouseClicked(evt);
            }
        });
        PatientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsBtnActionPerformed(evt);
            }
        });

        LabTestsBtn.setBackground(new java.awt.Color(255, 0, 0));
        LabTestsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        LabTestsBtn.setForeground(new java.awt.Color(255, 255, 255));
        LabTestsBtn.setText("Lab Tests");
        LabTestsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        LabTestsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTestsBtnMouseClicked(evt);
            }
        });
        LabTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabTestsBtnActionPerformed(evt);
            }
        });

        InventoryBtn.setBackground(new java.awt.Color(255, 0, 0));
        InventoryBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        InventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        InventoryBtn.setText("Inventory");
        InventoryBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        InventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseClicked(evt);
            }
        });
        InventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryBtnActionPerformed(evt);
            }
        });

        TreatmentBtn.setBackground(new java.awt.Color(255, 0, 0));
        TreatmentBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TreatmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        TreatmentBtn.setText("Treatment");
        TreatmentBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        TreatmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentBtnMouseClicked(evt);
            }
        });
        TreatmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreatmentBtnActionPerformed(evt);
            }
        });

        Treatment_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/remedy.png"))); // NOI18N
        Treatment_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Treatment_imgMouseClicked(evt);
            }
        });

        Logout_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/entry-door.png"))); // NOI18N
        Logout_img1.setAlignmentY(0.0F);
        Logout_img1.setMaximumSize(new java.awt.Dimension(50, 50));
        Logout_img1.setMinimumSize(new java.awt.Dimension(50, 50));
        Logout_img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_img1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(Logo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MedicalStaff_img)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PatientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabTestsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TreatmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Patients_img)
                        .addGap(132, 132, 132))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabTests_img, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Inventory_img, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Treatment_img)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logo)
                .addGap(57, 57, 57)
                .addComponent(MedicalStaff_img)
                .addGap(0, 0, 0)
                .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Patients_img)
                .addGap(0, 0, 0)
                .addComponent(PatientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(LabTests_img)
                .addGap(0, 0, 0)
                .addComponent(LabTestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Inventory_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Treatment_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TreatmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPositionCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDepartmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EmployeeId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(EmployeeName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ENameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(EmployeePhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(EmployeeAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(EmployeePosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EPositionCb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Department)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EDepartmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(UpdateMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(DeleteMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


//variabile globale
private Connection Con = null;
private PreparedStatement pst = null;
private ResultSet Rs = null;
private Statement St = null;

public static void setActiveButton(JButton newActiveButton) {
        // Resetam butonul anterior (dacă exista)
        if (activeButton != null) {
            activeButton.setBackground(null);
        }

        // Setam noul buton activ
        newActiveButton.setBackground(new java.awt.Color(0, 100, 0));
        activeButton = newActiveButton; 
    }

private void DisplayMedicalStaff(){ 
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT * FROM medical_staff");

        // Definirea modelului de tabel cu anteturi personalizate
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Employee ID", "Employee Name", "Employee Phone", "Employee Address", "Position", "Department"});

        // Adaugam randurile din ResultSet
        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("employee_id"),
                Rs.getString("employee_name"),
                Rs.getInt("employee_phone"),
                Rs.getString("employee_address"),
                Rs.getString("employee_position"),
                Rs.getString("department")
            });
        }

        // Setam modelul in tabel
        MedicalStaffTable.setModel(model);
        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void filterById() {
    String prefix = EIdTb.getText().trim();

    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

        // Daca prefixul este gol, afisam tot
        if (prefix.isEmpty()) {
            DisplayMedicalStaff();
        } else {
            // Construim interogarea cu LIKE pentru a potrivi prefixul
            String query = "SELECT * FROM medical_staff WHERE CAST(employee_id AS CHAR) LIKE ?";
            pst = Con.prepareStatement(query);
            pst.setString(1, prefix + "%"); // orice ID care începe cu prefix

            Rs = pst.executeQuery();

            // Construim un DefaultTableModel cu coloanele personalizate
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{
                    "Employee ID",
                    "Employee Name",
                    "Employee Phone",
                    "Employee Address",
                    "Position",
                    "Department"
            });

            // Adaugam randurile rezultate
            while (Rs.next()) {
                model.addRow(new Object[]{
                        Rs.getInt("employee_id"),
                        Rs.getString("employee_name"),
                        Rs.getInt("employee_phone"),
                        Rs.getString("employee_address"),
                        Rs.getString("employee_position"),
                        Rs.getString("department")
                });
            }

            // Actualizam tabelul
            MedicalStaffTable.setModel(model);
        }

        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void EIdTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIdTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIdTbActionPerformed

    private void ENameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ENameTbActionPerformed

    private void EAddressTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAddressTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAddressTbActionPerformed

    private void EPositionCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPositionCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPositionCbActionPerformed

    private void EDepartmentCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDepartmentCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDepartmentCbActionPerformed

    private void UpdateMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateMedBtnActionPerformed

    private void DeleteMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMedBtnActionPerformed

    private void EPhoneTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPhoneTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPhoneTbActionPerformed

    private void Clear() {
    EIdTb.setText("");
    ENameTb.setText("");
    EPhoneTb.setText("");
    EAddressTb.setText("");
    EPositionCb.setSelectedIndex(0);
    EDepartmentCb.setSelectedIndex(0);
    Key = 0;
}
    
    private void AddMedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMedBtnMouseClicked
    if (EIdTb.getText().isEmpty() || ENameTb.getText().isEmpty() || EPhoneTb.getText().isEmpty() || EAddressTb.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Missing Information");
    } else {
        try {
            boolean isEmployeeIdValid = true;
            boolean isEmployeeNameValid = true;
            boolean isEmployeePhoneValid = true;
            
            int employeeId = 0;
            int employeePhone = 0;
            String employeeName = ENameTb.getText();

            // Validare pentru Employee ID
            try {
                employeeId = Integer.parseInt(EIdTb.getText());
            } catch (NumberFormatException e) {
                isEmployeeIdValid = false;
            }

            // Validare pentru Employee Phone
            try {
                employeePhone = Integer.parseInt(EPhoneTb.getText());
            } catch (NumberFormatException e) {
                isEmployeePhoneValid = false;
            }

            // Validare pentru Employee Name (verificare daca sunt doar litere)
            if (!employeeName.matches("[a-zA-Z ]+")) {
                isEmployeeNameValid = false;
            }

            // Mesaje de eroare pentru campurile invalide
            if (!isEmployeeIdValid && !isEmployeePhoneValid && !isEmployeeNameValid) {
                JOptionPane.showMessageDialog(this, "Please enter valid values for Employee ID, Name, and Phone.");
                return;
            } else if (!isEmployeeIdValid && !isEmployeePhoneValid) {
                JOptionPane.showMessageDialog(this, "Please enter valid numbers for Employee ID and Phone.");
                return;
            } else if (!isEmployeeIdValid && !isEmployeeNameValid) {
                JOptionPane.showMessageDialog(this, "Employee ID should be a valid number and Employee Name should only contain letters.");
                return;
            } else if (!isEmployeePhoneValid && !isEmployeeNameValid) {
                JOptionPane.showMessageDialog(this, "Employee Phone should be a valid number and Employee Name should only contain letters.");
                return;
            } else if (!isEmployeeIdValid) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number for Employee ID.");
                return;
            } else if (!isEmployeePhoneValid) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number for Employee Phone.");
                return;
            } else if (!isEmployeeNameValid) {
                JOptionPane.showMessageDialog(this, "Employee Name should only contain letters.");
                return;
            }

            // Conectare la baza de date
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

            // Verificam daca angajatul exista deja
            String CheckQuery = "SELECT * FROM medical_staff WHERE employee_id = ?";
            PreparedStatement CheckStmt = Con.prepareStatement(CheckQuery);
            CheckStmt.setInt(1, employeeId);
            ResultSet RsCheck = CheckStmt.executeQuery();

            if (RsCheck.next()) {
                // Angajatul exista deja
                JOptionPane.showMessageDialog(this, "This staff member already exists. Use the Update Staff button to modify details.");
            } else {
                // Angajatul nu exista, adaugam unul nou
                String Query = "INSERT INTO medical_staff (employee_id, employee_name, employee_phone, employee_address, employee_position, department) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement Add = Con.prepareStatement(Query);
                Add.setInt(1, employeeId);
                Add.setString(2, ENameTb.getText());
                Add.setInt(3, employeePhone);
                Add.setString(4, EAddressTb.getText());
                Add.setString(5, EPositionCb.getSelectedItem().toString());
                Add.setString(6, EDepartmentCb.getSelectedItem().toString());

                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Medical Staff Added Successfully");

                // Reimprospatam tabelul și golim campurile
                DisplayMedicalStaff();
                Clear();
            }

            Con.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_AddMedBtnMouseClicked
 }
    
    private int Key = 0;
    
    private void DeleteMedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMedBtnMouseClicked
    if (Key == 0) {
        JOptionPane.showMessageDialog(this, "Select a Medical Staff to Delete");
    } else {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
            String Query = "DELETE FROM medical_staff WHERE employee_id = ?";
            PreparedStatement Delete = Con.prepareStatement(Query);
            Delete.setInt(1, Key);

            int row = Delete.executeUpdate();
            JOptionPane.showMessageDialog(this, "Medical Staff Deleted Successfully");

            DisplayMedicalStaff();
            Clear();

            Con.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }          
    }//GEN-LAST:event_DeleteMedBtnMouseClicked


    private void UpdateMedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMedBtnMouseClicked
    if (Key == 0) {
        JOptionPane.showMessageDialog(this, "Select a Medical Staff to Update");
    } else {
        try {
            int employeePhone = Integer.parseInt(EPhoneTb.getText());

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

            String Query = "UPDATE medical_staff SET employee_name = ?, employee_phone = ?, employee_address = ?, employee_position = ?, department = ? WHERE employee_id = ?";
            PreparedStatement Update = Con.prepareStatement(Query);
            Update.setString(1, ENameTb.getText());
            Update.setInt(2, employeePhone);
            Update.setString(3, EAddressTb.getText());
            Update.setString(4, EPositionCb.getSelectedItem().toString());
            Update.setString(5, EDepartmentCb.getSelectedItem().toString());
            Update.setInt(6, Key);

            int row = Update.executeUpdate();
            JOptionPane.showMessageDialog(this, "Medical Staff Updated Successfully");

            DisplayMedicalStaff();
            Clear();

            Con.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for Phone.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }  
    }//GEN-LAST:event_UpdateMedBtnMouseClicked

    private void MedicalStaffTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaffTableMouseClicked
    DefaultTableModel model = (DefaultTableModel) MedicalStaffTable.getModel();
    int MyIndex = MedicalStaffTable.getSelectedRow();
    EIdTb.setText(model.getValueAt(MyIndex, 0).toString());
    ENameTb.setText(model.getValueAt(MyIndex, 1).toString());
    EPhoneTb.setText(model.getValueAt(MyIndex, 2).toString());
    EAddressTb.setText(model.getValueAt(MyIndex, 3).toString());
    EPositionCb.setSelectedItem(model.getValueAt(MyIndex, 4).toString());
    EDepartmentCb.setSelectedItem(model.getValueAt(MyIndex, 5).toString());
    Key = Integer.parseInt(model.getValueAt(MyIndex, 0).toString());
    }//GEN-LAST:event_MedicalStaffTableMouseClicked

    private void MedicalStaff_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaff_imgMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaff_imgMouseClicked

    private void Patients_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patients_imgMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Patients_imgMouseClicked

    private void LabTests_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTests_imgMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTests_imgMouseClicked

    private void Inventory_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_imgMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Inventory_imgMouseClicked

    private void MedicalStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaffBtnMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaffBtnMouseClicked

    private void MedicalStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalStaffBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalStaffBtnActionPerformed

    private void PatientsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientsBtnMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientsBtnMouseClicked

    private void PatientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsBtnActionPerformed

    private void LabTestsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTestsBtnMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTestsBtnMouseClicked

    private void LabTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabTestsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabTestsBtnActionPerformed

    private void InventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventoryBtnMouseClicked

    private void InventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryBtnActionPerformed

    private void TreatmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentBtnMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TreatmentBtnMouseClicked

    private void TreatmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreatmentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TreatmentBtnActionPerformed

    private void Treatment_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Treatment_imgMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Treatment_imgMouseClicked

    private void Logout_img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_img1MouseClicked
        if (JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to leave?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
        ) == JOptionPane.YES_OPTION) {
        new Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_Logout_img1MouseClicked

    private void AddMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMedBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMedBtn;
    private javax.swing.JButton DeleteMedBtn;
    private javax.swing.JLabel Department;
    private javax.swing.JTextField EAddressTb;
    private javax.swing.JComboBox<String> EDepartmentCb;
    private javax.swing.JTextField EIdTb;
    private javax.swing.JTextField ENameTb;
    private javax.swing.JTextField EPhoneTb;
    private javax.swing.JComboBox<String> EPositionCb;
    private javax.swing.JLabel EmployeeAddress;
    private javax.swing.JLabel EmployeeId;
    private javax.swing.JLabel EmployeeName;
    private javax.swing.JLabel EmployeePhone;
    private javax.swing.JLabel EmployeePosition;
    private javax.swing.JButton InventoryBtn;
    private javax.swing.JLabel Inventory_img;
    private javax.swing.JButton LabTestsBtn;
    private javax.swing.JLabel LabTests_img;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logout_img1;
    private javax.swing.JButton MedicalStaffBtn;
    private javax.swing.JTable MedicalStaffTable;
    private javax.swing.JLabel MedicalStaff_img;
    private javax.swing.JButton PatientsBtn;
    private javax.swing.JLabel Patients_img;
    private javax.swing.JLabel Title;
    private javax.swing.JButton TreatmentBtn;
    private javax.swing.JLabel Treatment_img;
    private javax.swing.JButton UpdateMedBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
