/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


public class Patients extends javax.swing.JFrame {

    public Patients() {
        initComponents();
        
        PIdTb.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filterById();
            }
        });
        
        DisplayPatients();
        MedicalStaff.setActiveButton(PatientsBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        PIdTb = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        PNameTb = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        PAddressTb = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        PGenderCb = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        PDepartmentCb = new javax.swing.JComboBox<>();
        AddPatientBtn = new javax.swing.JButton();
        UpdatePatientBtn = new javax.swing.JButton();
        DeletePatientBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        PPhoneTb = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        PatientsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MedicalStaff_img = new javax.swing.JLabel();
        Patients_img = new javax.swing.JLabel();
        LabTests_img = new javax.swing.JLabel();
        Inventory_img = new javax.swing.JLabel();
        MedicalStaffBtn = new javax.swing.JButton();
        PatientsBtn = new javax.swing.JButton();
        LabTestsBtn = new javax.swing.JButton();
        InventoryBtn = new javax.swing.JButton();
        TreatmentBtn = new javax.swing.JButton();
        Treatment_img = new javax.swing.JLabel();
        Logout_img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Patient ID");

        PIdTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PIdTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PIdTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIdTbActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Patient Name");

        PNameTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PNameTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PNameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNameTbActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Patient Address");

        PAddressTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PAddressTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PAddressTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAddressTbActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Patient Gender");

        PGenderCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PGenderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        PGenderCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PGenderCbActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Department");

        PDepartmentCb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PDepartmentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "Radiology", "Dermatology", "Neurology", "Ophthalmology", "Pediatrics", "Urology", "Endocrinology", " " }));
        PDepartmentCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDepartmentCbActionPerformed(evt);
            }
        });

        AddPatientBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        AddPatientBtn.setForeground(new java.awt.Color(51, 204, 0));
        AddPatientBtn.setText("Add Patient");
        AddPatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPatientBtnMouseClicked(evt);
            }
        });
        AddPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientBtnActionPerformed(evt);
            }
        });

        UpdatePatientBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        UpdatePatientBtn.setForeground(new java.awt.Color(204, 204, 0));
        UpdatePatientBtn.setText("Update Patient");
        UpdatePatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatePatientBtnMouseClicked(evt);
            }
        });
        UpdatePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePatientBtnActionPerformed(evt);
            }
        });

        DeletePatientBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        DeletePatientBtn.setForeground(new java.awt.Color(255, 0, 0));
        DeletePatientBtn.setText("Delete Patient");
        DeletePatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletePatientBtnMouseClicked(evt);
            }
        });
        DeletePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePatientBtnActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Patient Phone");

        PPhoneTb.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PPhoneTb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PPhoneTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPhoneTbActionPerformed(evt);
            }
        });

        PatientsTable.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PatientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Patient Phone", "Patient Address", "Gender", "Department"
            }
        ));
        PatientsTable.setRowHeight(32);
        PatientsTable.setShowHorizontalLines(true);
        PatientsTable.setShowVerticalLines(true);
        PatientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PatientsTable);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 526));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/hospital (2).png"))); // NOI18N

        MedicalStaff_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\nurse-male.png")); // NOI18N
        MedicalStaff_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaff_imgMouseClicked(evt);
            }
        });

        Patients_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\patient.png")); // NOI18N
        Patients_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patients_imgMouseClicked(evt);
            }
        });

        LabTests_img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dragos Daniel\\Downloads\\atom.png")); // NOI18N
        LabTests_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTests_imgMouseClicked(evt);
            }
        });

        Inventory_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/first-aid-kit.png"))); // NOI18N
        Inventory_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_imgMouseClicked(evt);
            }
        });

        MedicalStaffBtn.setBackground(new java.awt.Color(255, 0, 0));
        MedicalStaffBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        MedicalStaffBtn.setForeground(new java.awt.Color(255, 255, 255));
        MedicalStaffBtn.setText("Medical Staff");
        MedicalStaffBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        MedicalStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicalStaffBtnMouseClicked(evt);
            }
        });
        MedicalStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalStaffBtnActionPerformed(evt);
            }
        });

        PatientsBtn.setBackground(new java.awt.Color(255, 0, 0));
        PatientsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        PatientsBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientsBtn.setText("Patients");
        PatientsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PatientsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        PatientsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientsBtnMouseClicked(evt);
            }
        });
        PatientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsBtnActionPerformed(evt);
            }
        });

        LabTestsBtn.setBackground(new java.awt.Color(255, 0, 0));
        LabTestsBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        LabTestsBtn.setForeground(new java.awt.Color(255, 255, 255));
        LabTestsBtn.setText("Lab Tests");
        LabTestsBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        LabTestsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabTestsBtnMouseClicked(evt);
            }
        });
        LabTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabTestsBtnActionPerformed(evt);
            }
        });

        InventoryBtn.setBackground(new java.awt.Color(255, 0, 0));
        InventoryBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        InventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        InventoryBtn.setText("Inventory");
        InventoryBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        InventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseClicked(evt);
            }
        });
        InventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryBtnActionPerformed(evt);
            }
        });

        TreatmentBtn.setBackground(new java.awt.Color(255, 0, 0));
        TreatmentBtn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        TreatmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        TreatmentBtn.setText("Treatment");
        TreatmentBtn.setMaximumSize(new java.awt.Dimension(104, 23));
        TreatmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentBtnMouseClicked(evt);
            }
        });
        TreatmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreatmentBtnActionPerformed(evt);
            }
        });

        Treatment_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/remedy.png"))); // NOI18N
        Treatment_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Treatment_imgMouseClicked(evt);
            }
        });

        Logout_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/entry-door.png"))); // NOI18N
        Logout_img1.setAlignmentY(0.0F);
        Logout_img1.setMaximumSize(new java.awt.Dimension(50, 50));
        Logout_img1.setMinimumSize(new java.awt.Dimension(50, 50));
        Logout_img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_img1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MedicalStaff_img)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PatientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabTestsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TreatmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Patients_img)
                        .addGap(132, 132, 132))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabTests_img, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Inventory_img, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Treatment_img)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(MedicalStaff_img)
                .addGap(0, 0, 0)
                .addComponent(MedicalStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Patients_img)
                .addGap(0, 0, 0)
                .addComponent(PatientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(LabTests_img)
                .addGap(0, 0, 0)
                .addComponent(LabTestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Inventory_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Treatment_img, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TreatmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(Logout_img1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PGenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PDepartmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdatePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeletePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PGenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PDepartmentCb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(UpdatePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(DeletePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;
    
    private void DisplayPatients() {
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT * FROM patients");

        // Definim un model de tabel cu anteturi personalizate
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Patient ID", "Patient Name", "Patient Phone", "Patient Address", "Gender", "Department"});

        // Adaugam randurile din ResultSet
        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("patient_id"),
                Rs.getString("patient_name"),
                Rs.getInt("patient_phone"),
                Rs.getString("patient_address"),
                Rs.getString("patient_gender"),
                Rs.getString("department")
            });
        }

        // Setam modelul în tabel
        PatientsTable.setModel(model);
        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void filterById() {
    String prefix = PIdTb.getText().trim();

    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

        // Daca prefixul este gol, afisam tot
        if (prefix.isEmpty()) {
            DisplayPatients();
        } else {
            // Construim interogarea cu LIKE pentru a potrivi prefixul
            String query = "SELECT * FROM patients WHERE CAST(patient_id AS CHAR) LIKE ?";
            pst = Con.prepareStatement(query);
            pst.setString(1, prefix + "%"); // orice ID care începe cu prefix

            Rs = pst.executeQuery();

            // Construim un DefaultTableModel cu coloanele personalizate
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"Patient ID", "Patient Name", "Patient Phone", "Patient Address", "Gender", "Department"});

            // Adaugam randurile rezultate
            while (Rs.next()) {
                model.addRow(new Object[]{
                Rs.getInt("patient_id"),
                Rs.getString("patient_name"),
                Rs.getInt("patient_phone"),
                Rs.getString("patient_address"),
                Rs.getString("patient_gender"),
                Rs.getString("department")
                });
            }

            // Actualizam tabelul
            PatientsTable.setModel(model);
        }

        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    
    private void PIdTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIdTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIdTbActionPerformed

    private void PNameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNameTbActionPerformed

    private void PAddressTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAddressTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAddressTbActionPerformed

    private void PGenderCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PGenderCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PGenderCbActionPerformed

    private void PDepartmentCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDepartmentCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDepartmentCbActionPerformed

    private void UpdatePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePatientBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatePatientBtnActionPerformed

    private void DeletePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePatientBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletePatientBtnActionPerformed

    private void PPhoneTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPhoneTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPhoneTbActionPerformed

    private void AddPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPatientBtnActionPerformed

    private void Clear() {
    PIdTb.setText("");
    PNameTb.setText("");
    PPhoneTb.setText("");
    PAddressTb.setText("");
    PGenderCb.setSelectedIndex(0);  
    PDepartmentCb.setSelectedIndex(0);
    Key = 0;  
}

    
    private void AddPatientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPatientBtnMouseClicked
        if (PIdTb.getText().isEmpty() || PNameTb.getText().isEmpty() || PPhoneTb.getText().isEmpty() || PAddressTb.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Missing Information");
    } else {
        try {
            boolean isPatientIdValid = true;
            boolean isPatientNameValid = true;
            boolean isPatientPhoneValid = true;

            int patientId = 0;
            int patientPhone = 0;
            String patientName = PNameTb.getText();

            // Validare pentru Patient ID
            try {
                patientId = Integer.parseInt(PIdTb.getText());
            } catch (NumberFormatException e) {
                isPatientIdValid = false;
            }

            // Validare pentru Patient Phone
            try {
                patientPhone = Integer.parseInt(PPhoneTb.getText());
            } catch (NumberFormatException e) {
                isPatientPhoneValid = false;
            }

            // Validare pentru Patient Name 
            if (!patientName.matches("[a-zA-Z ]+")) {
                isPatientNameValid = false;
            }

            // Mesaje de eroare pentru campurile invalide
            if (!isPatientIdValid && !isPatientPhoneValid && !isPatientNameValid) {
                JOptionPane.showMessageDialog(this, "Please enter valid values for Patient ID, Name, and Phone.");
                return;
            } else if (!isPatientIdValid && !isPatientPhoneValid) {
                JOptionPane.showMessageDialog(this, "Please enter valid numbers for Patient ID and Phone.");
                return;
            } else if (!isPatientIdValid && !isPatientNameValid) {
                JOptionPane.showMessageDialog(this, "Patient ID should be a valid number and Patient Name should only contain letters.");
                return;
            } else if (!isPatientPhoneValid && !isPatientNameValid) {
                JOptionPane.showMessageDialog(this, "Patient Phone should be a valid number and Patient Name should only contain letters.");
                return;
            } else if (!isPatientIdValid) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number for Patient ID.");
                return;
            } else if (!isPatientPhoneValid) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number for Patient Phone.");
                return;
            } else if (!isPatientNameValid) {
                JOptionPane.showMessageDialog(this, "Patient Name should only contain letters.");
                return;
            }

            // Conectare la baza de date
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

            // Verificam daca pacientul exista deja
            String CheckQuery = "SELECT * FROM patients WHERE patient_id = ?";
            PreparedStatement CheckStmt = Con.prepareStatement(CheckQuery);
            CheckStmt.setInt(1, patientId);
            ResultSet RsCheck = CheckStmt.executeQuery();

            if (RsCheck.next()) {
                // Pacientul exista deja
                JOptionPane.showMessageDialog(this, "This patient already exists. Use the Update Patient button to modify details.");
            } else {
                // Pacientul nu exista, adaugam unul nou
                String Query = "INSERT INTO patients (patient_id, patient_name, patient_phone, patient_address, patient_gender, department) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement Add = Con.prepareStatement(Query);
                Add.setInt(1, patientId);
                Add.setString(2, PNameTb.getText());
                Add.setInt(3, patientPhone);
                Add.setString(4, PAddressTb.getText());
                Add.setString(5, PGenderCb.getSelectedItem().toString());
                Add.setString(6, PDepartmentCb.getSelectedItem().toString());

                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Patient Added Successfully");

                // Reimprospatam tabelul și golim campurile
                DisplayPatients();
                Clear();
            }

            Con.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }
    }//GEN-LAST:event_AddPatientBtnMouseClicked

    private int Key = 0;
    
    private void DeletePatientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletePatientBtnMouseClicked
        if (Key == 0) {
        JOptionPane.showMessageDialog(this, "Select a Patient to Delete");
    } else {
        try {
            // Conectare la baza de date
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

            // Pregatim interogarea pentru ștergere
            String Query = "DELETE FROM patients WHERE patient_id = ?";
            PreparedStatement Delete = Con.prepareStatement(Query);
            Delete.setInt(1, Key);

            // Executam ștergerea
            int row = Delete.executeUpdate();
            JOptionPane.showMessageDialog(this, "Patient Deleted Successfully");

            // Reimprospatam tabelul și golim campurile
            DisplayPatients();
            Clear();

            Con.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }
    }//GEN-LAST:event_DeletePatientBtnMouseClicked

    private void UpdatePatientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatePatientBtnMouseClicked
        if (Key == 0) {
        JOptionPane.showMessageDialog(this, "Select a Patient to Update");
    } else {
        try {
            // Validam daca patient_phone este un numar
            int patientPhone = Integer.parseInt(PPhoneTb.getText());

            // Conectare la baza de date
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");

            // Pregatim interogarea pentru actualizare
            String Query = "UPDATE patients SET patient_name = ?, patient_phone = ?, patient_address = ?, patient_gender = ?, department = ? WHERE patient_id = ?";
            PreparedStatement Update = Con.prepareStatement(Query);
            Update.setString(1, PNameTb.getText());
            Update.setInt(2, patientPhone);
            Update.setString(3, PAddressTb.getText());
            Update.setString(4, PGenderCb.getSelectedItem().toString());
            Update.setString(5, PDepartmentCb.getSelectedItem().toString());
            Update.setInt(6, Key);

            int row = Update.executeUpdate();
            JOptionPane.showMessageDialog(this, "Patient Updated Successfully");

            DisplayPatients();
            Clear();

            Con.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for Phone.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }
    }//GEN-LAST:event_UpdatePatientBtnMouseClicked

    private void PatientsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientsTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) PatientsTable.getModel();
    int MyIndex = PatientsTable.getSelectedRow();

    // Preluam valorile din tabel
    PIdTb.setText(model.getValueAt(MyIndex, 0).toString());
    PNameTb.setText(model.getValueAt(MyIndex, 1).toString());
    PPhoneTb.setText(model.getValueAt(MyIndex, 2).toString());
    PAddressTb.setText(model.getValueAt(MyIndex, 3).toString());
    PGenderCb.setSelectedItem(model.getValueAt(MyIndex, 4).toString());
    PDepartmentCb.setSelectedItem(model.getValueAt(MyIndex, 5).toString());

    Key = Integer.parseInt(model.getValueAt(MyIndex, 0).toString());

    }//GEN-LAST:event_PatientsTableMouseClicked

    private void MedicalStaff_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaff_imgMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaff_imgMouseClicked

    private void Patients_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patients_imgMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Patients_imgMouseClicked

    private void LabTests_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTests_imgMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTests_imgMouseClicked

    private void Inventory_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_imgMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Inventory_imgMouseClicked

    private void MedicalStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicalStaffBtnMouseClicked
        new MedicalStaff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalStaffBtnMouseClicked

    private void MedicalStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalStaffBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalStaffBtnActionPerformed

    private void PatientsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientsBtnMouseClicked
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientsBtnMouseClicked

    private void PatientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientsBtnActionPerformed

    private void LabTestsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabTestsBtnMouseClicked
        new LabTests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabTestsBtnMouseClicked

    private void LabTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabTestsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabTestsBtnActionPerformed

    private void InventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseClicked
        new Inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventoryBtnMouseClicked

    private void InventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryBtnActionPerformed

    private void TreatmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentBtnMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TreatmentBtnMouseClicked

    private void TreatmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreatmentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TreatmentBtnActionPerformed

    private void Treatment_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Treatment_imgMouseClicked
        new Treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Treatment_imgMouseClicked

    private void Logout_img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_img1MouseClicked
        if (JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to leave?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
        ) == JOptionPane.YES_OPTION) {
        new Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_Logout_img1MouseClicked

   /* public DefaultTableModel getPatientsModel() {
    DefaultTableModel model = new DefaultTableModel();
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT * FROM patients");
        model.setColumnIdentifiers(new String[]{"Patient ID", "Patient Name", "Patient Phone", "Patient Address", "Gender", "Department"});
        while (Rs.next()) {
            model.addRow(new Object[]{
                Rs.getInt("patient_id"),
                Rs.getString("patient_name"),
                Rs.getInt("patient_phone"),
                Rs.getString("patient_address"),
                Rs.getString("patient_gender"),
                Rs.getString("department")
            });
        }
        Con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    return model;
}*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientBtn;
    private javax.swing.JButton DeletePatientBtn;
    private javax.swing.JButton InventoryBtn;
    private javax.swing.JLabel Inventory_img;
    private javax.swing.JButton LabTestsBtn;
    private javax.swing.JLabel LabTests_img;
    private javax.swing.JLabel Logout_img1;
    private javax.swing.JButton MedicalStaffBtn;
    private javax.swing.JLabel MedicalStaff_img;
    private javax.swing.JTextField PAddressTb;
    private javax.swing.JComboBox<String> PDepartmentCb;
    private javax.swing.JComboBox<String> PGenderCb;
    private javax.swing.JTextField PIdTb;
    private javax.swing.JTextField PNameTb;
    private javax.swing.JTextField PPhoneTb;
    private javax.swing.JButton PatientsBtn;
    private javax.swing.JTable PatientsTable;
    private javax.swing.JLabel Patients_img;
    private javax.swing.JButton TreatmentBtn;
    private javax.swing.JLabel Treatment_img;
    private javax.swing.JButton UpdatePatientBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
